apiVersion: kubedb.com/v1alpha2
kind: MsSQL
metadata:
  name: ag
  namespace: demo
spec:
  version: "latest"  # Specify the desired version, e.g., "2019-CU12-GDR" or "2017-CU24-GDR"
  replicas: 3        # Number of instances to deploy
  authSecret:
    name: mssql-custom-auth
  topology:
    mode: AvailabilityGroup
    availabilityGroup:
      name: myAG
      database: myAgDB
  storageType: Durable
  storage:
    storageClassName: "standard"
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
  terminationPolicy: Halt
