apiVersion: v1
kind: Service
metadata:
  name: sql-server-listener
  namespace: your-namespace
spec:
  selector:
    app: your-sql-server-app
  ports:
    - name: mssql
      port: 1433
      targetPort: 1433
  type: LoadBalancer  # or  or NodePort depending on your environment
