apiVersion: kubedb.com/v1alpha2
kind: MsSQL
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"kubedb.com/v1alpha2","kind":"MsSQL","metadata":{"annotations":{},"name":"ag-custom","namespace":"demo"},"spec":{"authSecret":{"externallyManaged":true,"name":"mssql-custom-auth"},"internalAuth":{"endpointCert":{"issuerRef":{"apiGroup":"cert-manager.io","kind":"Issuer","name":"postgres-ca-issuer"}}},"leaderElection":{"electionTick":10,"heartbeatTick":1,"period":"100ms","transferLeadershipInterval":"1s","transferLeadershipTimeout":"60s"},"replicas":2,"storage":{"accessModes":["ReadWriteOnce"],"resources":{"requests":{"storage":"1Gi"}},"storageClassName":"standard"},"storageType":"Durable","terminationPolicy":"Delete","topology":{"availabilityGroup":{"databases":["AgDB1","AgDB2"]},"mode":"AvailabilityGroup"},"version":"2022-cu12"}}
  creationTimestamp: "2024-04-05T11:00:49Z"
  finalizers:
  - kubedb.com
  generation: 2
  name: ag-custom
  namespace: demo
  resourceVersion: "2315656"
  uid: 84ce9b10-fcfc-4655-af84-a818f59650f0
spec:
  authSecret:
    name: mssql-custom-auth
  coordinator:
    resources: {}
  healthChecker:
    failureThreshold: 1
    periodSeconds: 10
    timeoutSeconds: 10
  internalAuth:
    endpointCert:
      issuerRef:
        apiGroup: cert-manager.io
        kind: Issuer
        name: postgres-ca-issuer
  leaderElection:
    electionTick: 10
    heartbeatTick: 1
    period: 100ms
    transferLeadershipInterval: 1s
    transferLeadershipTimeout: 1m0s
  podPlacementPolicy:
    name: default
  podTemplate:
    controller: {}
    metadata: {}
    spec:
      containers:
      - name: mssql
        resources:
          limits:
            memory: 1536Mi
          requests:
            cpu: 500m
            memory: 1536Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            add:
            - NET_BIND_SERVICE
            drop:
            - ALL
          runAsNonRoot: true
          seccompProfile:
            type: RuntimeDefault
      - name: mssql-coordinator
        resources:
          limits:
            memory: 256Mi
          requests:
            cpu: 200m
            memory: 256Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          runAsNonRoot: true
          seccompProfile:
            type: RuntimeDefault
      initContainers:
      - name: mssql-init
        resources:
          limits:
            memory: 512Mi
          requests:
            cpu: 200m
            memory: 512Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          runAsNonRoot: true
          seccompProfile:
            type: RuntimeDefault
      securityContext: {}
  replicas: 2
  storage:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
    storageClassName: standard
  storageType: Durable
  terminationPolicy: Delete
  topology:
    availabilityGroup:
      databases:
      - AgDB1
      - AgDB2
    mode: AvailabilityGroup
  version: 2022-cu12
status:
  conditions:
  - lastTransitionTime: "2024-04-05T11:00:49Z"
    message: 'The KubeDB operator has started the provisioning of MsSQL: demo/ag-custom'
    observedGeneration: 1
    reason: DatabaseProvisioningStartedSuccessfully
    status: "True"
    type: ProvisioningStarted
  - lastTransitionTime: "2024-04-05T11:00:50Z"
    message: Some replicas not ready for MsSQL demo/ag-custom
    observedGeneration: 2
    reason: SomeReplicasNotReady
    status: "False"
    type: ReplicaReady
  phase: Provisioning
