apiVersion: kubedb.com/v1alpha2
kind: MSSQLServer
metadata:
  name: ms-ag-mon
  namespace: demo
spec:
  version: "2022-cu12"
  replicas: 3
  topology:
    mode: AvailabilityGroup
    availabilityGroup:
      databases:
        - agdb1
        - agdb2
  internalAuth:
    endpointCert:
      issuerRef:
        apiGroup: cert-manager.io
        name: mssqlserver-ca-issuer
        kind: Issuer
  tls:
    issuerRef:
      name: mssqlserver-ca-issuer
      kind: Issuer
      apiGroup: "cert-manager.io"
    clientTLS: false
  monitor:
    agent: prometheus.io/operator
    prometheus:
      exporter:
        port: 9399
      serviceMonitor:
        labels:
          release: prometheus
        interval: 10s
  storageType: Durable
  storage:
    storageClassName: "standard" # "linode-block-storage" # 
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
  deletionPolicy: WipeOut
