apiVersion: kubedb.com/v1alpha2
kind: MSSQLServer
metadata:
  name: ms-notls
  namespace: demo
spec:
  deletionPolicy: WipeOut
  internalAuth:
    endpointCert:
      certificates:
      - alias: endpoint
        secretName: ms-notls-endpoint-cert
        subject:
          organizationalUnits:
          - endpoint
          organizations:
          - kubedb
      issuerRef:
        name: mssqlserver-ca-issuer
        kind: Issuer
        apiGroup: "cert-manager.io"
  monitor:
    agent: prometheus.io/operator
    prometheus:
      exporter:
        port: 56790
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
      serviceMonitor:
        interval: 30s
        labels:
          monitoring.appscode.com/prometheus: federated
  podTemplate:
    controller: {}
    metadata: {}
    spec:
      containers:
      - name: mssql
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
          requests:
            cpu: 500m
            memory: 1Gi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            add:
            - NET_BIND_SERVICE
            drop:
            - ALL
          runAsGroup: 10001
          runAsNonRoot: true
          runAsUser: 10001
          seccompProfile:
            type: RuntimeDefault
      - name: mssql-coordinator
        resources:
          limits:
            memory: 256Mi
          requests:
            cpu: 200m
            memory: 256Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          runAsGroup: 10001
          runAsNonRoot: true
          runAsUser: 10001
          seccompProfile:
            type: RuntimeDefault
      initContainers:
      - name: mssql-init
        resources:
          limits:
            memory: 512Mi
          requests:
            cpu: 200m
            memory: 512Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          runAsGroup: 10001
          runAsNonRoot: true
          runAsUser: 10001
          seccompProfile:
            type: RuntimeDefault
      podPlacementPolicy:
        name: default
      securityContext:
        fsGroup: 10001
  replicas: 3
  storage:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 10Gi
    storageClassName: linode-block-storage
  storageType: Durable
  tls:
    certificates:
    - alias: server
      secretName: ms-notls-server-cert
      subject:
        organizationalUnits:
        - server
        organizations:
        - kubedb
    - alias: client
      secretName: ms-notls-client-cert
      subject:
        organizationalUnits:
        - client
        organizations:
        - kubedb
    clientTLS: false
    issuerRef:
      name: mssqlserver-ca-issuer
      kind: Issuer
      apiGroup: "cert-manager.io"
  topology:
    availabilityGroup:
      databases: []
    mode: AvailabilityGroup
  version: 2022-cu12