apiVersion: catalog.kubedb.com/v1alpha1
kind: MSSQLServerVersion
metadata:
  name: 2022-cu19
spec:
  archiver:
    addon:
      name: mssqlserver-addon
      tasks:
        fullBackup:
          name: logical-backup
        fullBackupRestore:
          name: logical-backup-restore
        manifestBackup:
          name: manifest-backup
        manifestRestore:
          name: manifest-restore
    walg:
      image: ghcr.io/kubedb/mssqlserver-archiver:v0.11.0-rc.0
  coordinator:
    image: ghcr.io/kubedb/mssql-coordinator:v0.12.0-rc.0
  db:
    image: mcr.microsoft.com/mssql/server:2022-CU19-ubuntu-22.04
  exporter:
    image: ghcr.io/kubedb/mssql-exporter:1.1.0
  initContainer:
    image: neajmorshad/mssql-init:_linux_amd64
  securityContext:
    runAsUser: 10001
  version: "2022"
