apiVersion: kubedb.com/v1
kind: PerconaXtraDB
metadata:
  name: xtradb-galera
  namespace: demo
spec:
  version: "8.4.3"
  replicas: 3
  configSecret:
    name: px-configuration
  # podTemplate:
  #   spec:
  #     containers:
  #     - name: perconaxtradb
  #       securityContext:
  #         capabilities:
  #           add: ["SYS_NICE"]
  #           drop: ["ALL"]
  storageType: Durable
  storage:
    storageClassName: "standard"
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
  deletionPolicy: WipeOut