apiVersion: v1
kind: Service
metadata:
  name: qdrant-cluster-pods
spec:
  clusterIP: None
  selector:
    app: qdrant-cluster
  ports:
    - name: http
      port: 6333
    - name: grpc
      port: 6334
    - name: p2p
      port: 6335
---
apiVersion: v1
kind: Service
metadata:
  name: qdrant-cluster
spec:
  type: ClusterIP
  selector:
    app: qdrant-cluster
  ports:
    - name: http
      port: 6333
      targetPort: 6333
    - name: grpc
      port: 6334
      targetPort: 6334
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: qdrant-cluster
spec:
  serviceName: "qdrant-cluster-pods"
  replicas: 3
  selector:
    matchLabels:
      app: qdrant-cluster
  template:
    metadata:
      labels:
        app: qdrant-cluster
    spec:
      containers:
        - name: qdrant
          image: qdrant/qdrant:latest
          
          command: ["/bin/sh", "-c"]
          args:
            - |
              export QDRANT__P2P__URI="http://${POD_NAME}.qdrant-cluster-pods:6335"
              # ---------------------------------------------------------------- #
              # --- THIS IS THE FINAL FIX: USE THE ABSOLUTE PATH TO THE BINARY --- #
              # ---------------------------------------------------------------- #
              exec /qdrant/qdrant

          ports:
            - containerPort: 6333
              name: http
            - containerPort: 6334
              name: grpc
            - containerPort: 6335
              name: p2p
          
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            
            - name: QDRANT__CLUSTER__ENABLED
              value: "true"
            - name: QDRANT__CLUSTER__BOOTSTRAP_URI
              value: "http://qdrant-cluster-0.qdrant-cluster-pods:6335"
          
          volumeMounts:
            - name: qdrant-storage
              mountPath: /qdrant/storage

  volumeClaimTemplates:
    - metadata:
        name: qdrant-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 5Gi