new secret -> old one stays 


operator: 
secret annotations
db spec activeFrom 
 
 
 
 
 
 // ops major flow:
//    1. update in secret:
//    - if user provide a secret:
//        - we store current auth in user's provided secret's '.prev' data
//    - else
//        - we generate a new password and store new cred in existing secret's '.next' data
//    2. update password in nodes those have pvc(except hidden) by mongodb client:
//        - if secret is user provided, use external secret's 'password' data
//        - else use existing secret 'password.next' data(updated in step 1)
//    3. reconcile db with new dbCopy
//    4. restart all pods
//    5. if generate secret's password case, shift "current cred -> .prev cred" and ".next cred -> current cred"
 
 
apiVersion: ops.kubedb.com/v1alpha1
kind: MongoDBOpsRequest
metadata:
  name: mops-auth-rotate
  namespace: demo
spec:
  type: RotateAuth
  databaseRef:
    name: shard-mongodb8
  # authentication:
  #   secretRef:
  #     name: repl-auth-custom
  readinessCriteria:
    oplogMaxLagSeconds: 20
    objectsCountDiffPercentage: 10
  timeout: 5m
  apply: IfReady
 