apiVersion: kubedb.com/v1
kind: RedisSentinel
metadata:
  name: sentinel-v1
  namespace: demo
spec:
  version: 7.2.4
  replicas: 3
  storageType: Durable
  storage:
    resources:
      requests:
        storage: 1Gi
#    storageClassName: "standard"
    accessModes:
    - ReadWriteOnce
  podTemplate:
    spec:
      containers:
      - name: redissentinel
        resources:
          requests:
            cpu: 150m
            memory: 150Mi
  deletionPolicy: WipeOut
