apiVersion: v1
items:
- apiVersion: kubedb.com/v1alpha2
  kind: Redis
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"kubedb.com/v1alpha2","kind":"Redis","metadata":{"annotations":{},"name":"rd-sentinel","namespace":"demo"},"spec":{"mode":"Sentinel","replicas":3,"sentinelRef":{"name":"sen-demo","namespace":"demo"},"storage":{"accessModes":["ReadWriteOnce"],"resources":{"requests":{"storage":"1Gi"}},"storageClassName":"standard"},"storageType":"Durable","terminationPolicy":"DoNotTerminate","version":"7.2.0"}}
    creationTimestamp: "2023-10-12T05:37:29Z"
    finalizers:
    - kubedb.com
    generation: 2
    name: rd-sentinel
    namespace: demo
    resourceVersion: "1021215"
    uid: 3ae570b3-3f1d-433c-8856-7e7ab50d93bf
  spec:
    allowedSchemas:
      namespaces:
        from: Same
    authSecret:
      name: rd-sentinel-auth
    autoOps: {}
    coordinator:
      resources: {}
    healthChecker:
      failureThreshold: 1
      periodSeconds: 10
      timeoutSeconds: 10
    mode: Sentinel
    podTemplate:
      controller: {}
      metadata: {}
      spec:
        affinity:
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/instance: rd-sentinel
                    app.kubernetes.io/managed-by: kubedb.com
                    app.kubernetes.io/name: redises.kubedb.com
                namespaces:
                - demo
                topologyKey: kubernetes.io/hostname
              weight: 100
            - podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/instance: rd-sentinel
                    app.kubernetes.io/managed-by: kubedb.com
                    app.kubernetes.io/name: redises.kubedb.com
                namespaces:
                - demo
                topologyKey: failure-domain.beta.kubernetes.io/zone
              weight: 50
        resources:
          limits:
            memory: 1Gi
          requests:
            cpu: 500m
            memory: 1Gi
        serviceAccountName: rd-sentinel
    replicas: 3
    sentinelRef:
      name: sen-demo
      namespace: demo
    storage:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
      storageClassName: standard
    storageType: Durable
    terminationPolicy: DoNotTerminate
    version: 7.2.0
  status:
    conditions:
    - lastTransitionTime: "2023-10-12T05:37:30Z"
      message: 'The KubeDB operator has started the provisioning of Redis: demo/rd-sentinel'
      reason: DatabaseProvisioningStartedSuccessfully
      status: "True"
      type: ProvisioningStarted
    - lastTransitionTime: "2023-10-12T05:37:52Z"
      message: All desired replicas are ready.
      reason: AllReplicasReady
      status: "True"
      type: ReplicaReady
    - lastTransitionTime: "2023-10-12T05:38:06Z"
      message: 'The Redis: demo/rd-sentinel is accepting rdClient requests.'
      observedGeneration: 2
      reason: DatabaseAcceptingConnectionRequest
      status: "True"
      type: AcceptingConnection
    - lastTransitionTime: "2023-10-12T05:38:16Z"
      message: 'The Redis: demo/rd-sentinel is ready.'
      observedGeneration: 2
      reason: ReadinessCheckSucceeded
      status: "True"
      type: Ready
    - lastTransitionTime: "2023-10-12T05:38:21Z"
      message: 'The Redis: demo/rd-sentinel is successfully provisioned.'
      observedGeneration: 2
      reason: DatabaseSuccessfullyProvisioned
      status: "True"
      type: Provisioned
    observedGeneration: 2
    phase: Ready
kind: List
metadata:
  resourceVersion: ""
