apiVersion: kubedb.com/v1
kind: RedisSentinel
metadata:
  name: sentinel-v1
  namespace: demo
spec:
  version: 7.4.0
  replicas: 3
  tls:
    issuerRef:
      apiGroup: "cert-manager.io"
      kind: Issuer
      name: redis-ca-issuer
  storageType: Durable
  storage:
    resources:
      requests:
        storage: 1Gi
    storageClassName: "linode-block-storage" # "standard" # "longhorn"
    accessModes:
    - ReadWriteOnce
  monitor:
    agent: prometheus.io/operator
    prometheus:
      exporter:
        resources:
          requests:
            cpu: "150m"
            memory: "150Mi"
      serviceMonitor:
        labels:
          release: prometheus
        interval: 10s
  podTemplate:
    spec:
      containers:
      - name: redissentinel
        resources:
          requests:
            cpu: 150m
            memory: 150Mi
          limits:
            cpu: "200m"
            memory: "200Mi"
  deletionPolicy: WipeOut
