apiVersion: kubedb.com/v1alpha2
kind: RedisSentinel
metadata:
  name: sentinel
  namespace: demo
spec:
  version: 7.2.4
  replicas: 3
  storageType: Durable
  storage:
    resources:
      requests:
        storage: 1Gi
    storageClassName: "linode-block-storage" # "standard" # "longhorn"
    accessModes:
    - ReadWriteOnce
  podTemplate:
    spec:
      resources:
        requests:
          cpu: "150m"
          memory: "150Mi"
  monitor:
    agent: prometheus.io/operator
    prometheus:
      exporter:
        resources:
          requests:
            cpu: "150m"
            memory: "150Mi"
      serviceMonitor:
        labels:
          release: prometheus
        interval: 10s
  terminationPolicy: WipeOut
