apiVersion: kubedb.com/v1alpha2
kind: Redis
metadata:
  name: rd-sentinel
  namespace: demo
spec:
  version: 7.2.4
  replicas: 3
  sentinelRef:
    name: sen-demo
    namespace: demo
  mode: Sentinel
  storageType: Durable
  storage:
    resources:
      requests:
        storage: 1Gi
    storageClassName: "standard"
    accessModes:
      - ReadWriteOnce
  terminationPolicy: WipeOut
