apiVersion: kubedb.com/v1alpha2
kind: Redis
metadata:
  name: redis-cluster-res
  namespace: demo
spec:
  version: 5.0.14
  mode: Cluster
  cluster:
    master: 3
    replicas: 1
  storageType: Durable
  storage:
    resources:
      requests:
        storage: 1Gi
    storageClassName: "standard"
    accessModes:
    - ReadWriteOnce
  podTemplate:
    spec:
      resources:
        requests:
          cpu: "100m"
          memory: "100Mi"
  terminationPolicy: Halt
