apiVersion: kubedb.com/v1alpha2
kind: Redis
metadata:
  name: redis-using-ex-auth
  namespace: demo
spec:
  version: 6.2.5
  mode: Cluster
  cluster:
    master: 3
    replicas: 1
  authSecret:
    name: mysecret-test
    externallyManaged: true
  storageType: Durable
  storage:
    resources:
      requests:
        storage: 1Gi
    storageClassName: "standard"
    accessModes:
    - ReadWriteOnce
  terminationPolicy: Halt
