apiVersion: kubedb.com/v1alpha2
kind: Redis
metadata:
  name: redis-standalone
  namespace: demo
spec:
  version: 7.0.9
  storageType: Durable
  podTemplate:
    spec:
      initContainers:
      - name: hello
        image: alpine
        args: ["/bin/sh", "-c", "echo hello-world"]
  storage:
    storageClassName: "standard"
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
  terminationPolicy: WipeOut
