apiVersion: kubedb.com/v1
kind: Redis
metadata:
  name: rd-cluster-v1-tls
  namespace: demo
spec:
  version: 7.4.0
  mode: Cluster
  tls:
    issuerRef:
      apiGroup: "cert-manager.io"
      kind: Issuer
      name: redis-ca-issuer
  cluster:
    shards: 3
    replicas: 2
  storageType: Durable
  storage:
    resources:
      requests:
        storage: 1Gi
    storageClassName: "standard"
    accessModes:
    - ReadWriteOnce
  podTemplate:
    spec:
      containers:
      - name: redis
        resources:
          requests:
            cpu: 150m
            memory: 150Mi

  deletionPolicy: WipeOut
  monitor:
    agent: prometheus.io/operator
    prometheus:
      exporter:
        resources:
          requests:
            cpu: "150m"
            memory: "150Mi"
      serviceMonitor:
        labels:
          release: prometheus
        interval: 10s
