apiVersion: kubedb.com/v1
kind: Redis
metadata:
  name: rd-cluster-v1-res
  namespace: demo
spec:
  version: 7.4.0
  mode: Cluster
  cluster:
    shards: 3
    replicas: 2
  storageType: Durable
  storage:
    resources:
      requests:
        storage: 1Gi
    storageClassName: "linode-block-storage" #  #  # "longhorn"
    accessModes:
    - ReadWriteOnce
  podTemplate:
    spec:
      containers:
      - name: redis
        resources:
          requests:
            cpu: 150m
            memory: 150Mi
  deletionPolicy: WipeOut
