apiVersion: kubedb.com/v1
kind: Redis
metadata:
  name: rd-sentinel
  namespace: demo
spec:
  version: 7.4.1
  # replicas: 3
  sentinelRef:
    name: sentinel
    namespace: demo
  mode: Sentinel
  # tls:
  #   issuerRef:
  #     apiGroup: "cert-manager.io"
  #     kind: Issuer
  #     name: redis-ca-issuer
  storageType: Durable
  storage:
    resources:
      requests:
        storage: 1Gi
    storageClassName: "longhorn" # "standard" # "longhorn"
    accessModes:
      - ReadWriteOnce
  monitor:
    agent: prometheus.io/operator
    prometheus:
      exporter:
        resources:
          requests:
            cpu: "150m"
            memory: "150Mi"
      serviceMonitor:
        labels:
          release: prometheus
        interval: 10s
  podTemplate:
    spec:
      containers:
      - name: redis
        resources:
          requests:
            cpu: 150m
            memory: 150Mi
      - name: rd-coordinator
        resources:
          requests:
            cpu: 150m
            memory: 150Mi
  deletionPolicy: WipeOut
