apiVersion: kubedb.com/v1
kind: Redis
metadata:
  name: rd-sentinel-v1
  namespace: demo
spec:
  version: 7.2.4
  replicas: 3
  sentinelRef:
    name: sentinel-v1
    namespace: demo
  mode: Sentinel
  storageType: Durable
  storage:
    resources:
      requests:
        storage: 1Gi
#    storageClassName: "standard"
    accessModes:
      - ReadWriteOnce
  podTemplate:
    spec:
      containers:
      - name: redis
        resources:
          requests:
            cpu: 150m
            memory: 150Mi
      - name: rd-coordinator
        resources:
          requests:
            cpu: 150m
            memory: 150Mi
  deletionPolicy: WipeOut
