apiVersion: kubedb.com/v1alpha2
kind: Redis
metadata:
  name: rd-stand
  namespace: demo
spec:
  version: 7.2.4
  storageType: Durable
  storage:
    storageClassName: "linode-block-storage" # "standard" # "longhorn"
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
  podTemplate:
    spec:
      resources:
        requests:
          cpu: "150m"
          memory: "150Mi"
  terminationPolicy: WipeOut
