apiVersion: kubedb.com/v1alpha2
kind: Redis
metadata:
  name: rd-stand-mon
  namespace: demo
spec:
  version: 7.2.3
  storageType: Durable
  storage:
    # storageClassName: "standard"
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
  podTemplate:
    spec:
      resources:
        requests:
          cpu: "150m"
          memory: "150Mi"
  terminationPolicy: WipeOut
  monitor:
    agent: prometheus.io/operator
    prometheus:
      exporter:
        resources:
          requests:
            cpu: "150m"
            memory: "150Mi"
      serviceMonitor:
        labels:
          release: prometheus
        interval: 10s