apiVersion: kubedb.com/v1
kind: Redis
metadata:
  name: rd-stand-v1
  namespace: demo
spec:
  version: 7.2.4
  storageType: Durable
  storage:
    # storageClassName: "standard"
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
  podTemplate:
    spec:
      containers:
      - name: redis
        resources:
          requests:
            cpu: 150m
            memory: 150Mi
  deletionPolicy: WipeOut
