apiVersion: kubedb.com/v1alpha2
kind: Redis
metadata:
  name: rd-std
  namespace: demo
spec:
  version: 7.2.3
  storageType: Durable
  storage:
    storageClassName: "standard"
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
  podTemplate:
    spec:
      resources:
        requests:
          cpu: "100m"
          memory: "100Mi"
  terminationPolicy: WipeOut
