apiVersion: kubedb.com/v1
kind: Redis
metadata:
  name: rd-stand-v1
  namespace: demo
spec:
  version: 7.2.4
  # authSecret:
  #   name: mysecret
  #   externallyManaged: true

  # tls:
  #   issuerRef:
  #     apiGroup: "cert-manager.io"
  #     kind: Issuer
  #     name: redis-ca-issuer
  storageType: Durable
  storage:
    storageClassName: "standard"
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
  podTemplate:
    spec:
      containers:
      - name: redis
        resources:
          requests:
            cpu: 150m
            memory: 150Mi
          limits:
            cpu: "300m"
            memory: "300Mi"
  # monitor:
  #   agent: prometheus.io/operator
  #   prometheus:
  #     exporter:
  #       resources:
  #         requests:
  #           cpu: "150m"
  #           memory: "150Mi"
  #     serviceMonitor:
  #       labels:
  #         release: prometheus
  #       interval: 10s
  deletionPolicy: WipeOut

