apiVersion: kubedb.com/v1alpha2
kind: Redis
metadata:
  name: rd-std-tls
  namespace: demo
spec:
  version: 7.2.3
  tls:
    issuerRef:
      apiGroup: "cert-manager.io"
      kind: Issuer
      name: redis-ca-issuer
  storage:
    storageClassName: "standard"
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
