apiVersion: kubedb.com/v1alpha2
kind: Redis
metadata:
  name: rd-sentinel
  namespace: demo
spec:
  version: 7.2.4
  replicas: 3
  sentinelRef:
    name: sentinel
    namespace: demo
  mode: Sentinel
  storageType: Durable
  storage:
    resources:
      requests:
        storage: 1Gi
    storageClassName: "linode-block-storage" # "standard" # "longhorn"
    accessModes:
      - ReadWriteOnce
  coordinator:
    resources:
        requests:
          cpu: "150m"
          memory: "150Mi"
  podTemplate:
    spec:
      resources:
        requests:
          cpu: "150m"
          memory: "150Mi"
  terminationPolicy: WipeOut