apiVersion: v1
kind: Service
metadata:
  name: rd-tls
  namespace: cpp
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/instance: rd-tls  # Make sure this selector matches the labels of your Redis pods
  ports:
  - protocol: TCP
    port: 6379  # The port you want to expose
    targetPort: 6379  # The port
