apiVersion: addons.kubestash.com/v1alpha1
kind: Function
metadata:
  name: workload-restore
spec:
  image: neajmorshad/workload:0c1dc11_linux_amd64
  args:
  - restore
  - --namespace=${namespace:=default}
  - --restoresession=${restoreSession:=}
  - --snapshot=${snapshot:=}
  - --exclude=${exclude:=}
  - --include=${include:=}
