apiVersion: autoscaling.kubedb.com/v1alpha1
kind: MSSQLServerAutoscaler
metadata:
  name: ms-as-storage
  namespace: demo
spec:
  databaseRef:
    name: mssql-standalone
  storage:
    mssqlserver:
      trigger: "On" # If “On” then compute autoscaling is enabled. If “Off” then compute autoscaling is disabled
      usageThreshold: 60
      scalingThreshold: 50
      expansionMode: "Offline"
      upperBound: "100Gi"