# apiVersion: ops.kubedb.com/v1alpha1
# kind: MSSQLServerOpsRequest
# metadata:
#   name: msops-reconfigure-standalone
#   namespace: demo
# spec:
#   type: Reconfigure
#   databaseRef:
#     name: ms-standalone
#   configuration:
#       configSecret:
#         name: new-custom-config
#   timeout: 5m
#   apply: IfReady



apiVersion: ops.kubedb.com/v1alpha1
kind: MSSQLServerOpsRequest
metadata:
  name: msops-reconfigure-standalone-apply
  namespace: demo
spec:
  type: Reconfigure
  databaseRef:
    name: ms-standalone
  configuration:
    applyConfig:
      mssql.conf: |-
        [memory]
        memorylimitmb = 3072
  timeout: 5m
  apply: IfReady