# apiVersion: ops.kubedb.com/v1alpha1
# kind: MSSQLServerOpsRequest
# metadata:
#   name: msops-add-tls
#   namespace: demo
# spec:
#   type: ReconfigureTLS
#   databaseRef:
#     name: ms-standalone
#   tls:
#     issuerRef:
#       name: mssqlserver-ca-issuer
#       kind: Issuer
#       apiGroup: "cert-manager.io"
#     certificates:
#       - alias: client
#         subject:
#           organizations:
#             - mssqlserver
#           organizationalUnits:
#             - client
#     clientTLS: true
#   timeout: 5m
#   apply: IfReady

apiVersion: ops.kubedb.com/v1alpha1
kind: MSSQLServerOpsRequest
metadata:
  name: msops-rotate
  namespace: demo
spec:
  type: ReconfigureTLS
  databaseRef:
    name: ms-standalone
  tls:
    rotateCertificates: true
    clientTLS: true
  timeout: 5m
  apply: IfReady




# Remove TLS from the Database
  # tls:
  #   remove: true


# Change Issuer/ClusterIssuer
  # tls:
  #   issuerRef:
  #     name: rd-new-issuer
  #     kind: Issuer
  #     apiGroup: "cert-manager.io"

# Add TLS
    # tls:
    # issuerRef:
    #   name: redis-ca-issuer
    #   kind: Issuer
    #   apiGroup: "cert-manager.io"
    # certificates:
    #   - alias: client
    #     subject:
    #       organizations:
    #         - redis
    #       organizationalUnits:
    #         - client


# Rotate Certificate
  # tls:
  #   rotateCertificates: true








  # mssqlserver tls spec example

 # tls:
 #    certificates:
 #    - alias: server
 #      secretName: mssql-standalone-server-cert
 #      subject:
 #        organizationalUnits:
 #        - server
 #        organizations:
 #        - kubedb
 #    - alias: client
 #      secretName: mssql-standalone-client-cert
 #      subject:
 #        organizationalUnits:
 #        - client
 #        organizations:
 #        - kubedb
 #    clientTLS: false
 #    issuerRef:
 #      apiGroup: cert-manager.io
 #      kind: Issuer
 #      name: mssqlserver-ca-issuer
