apiVersion: ops.kubedb.com/v1alpha1
kind: MSSQLServerOpsRequest
metadata:
  name: msops-restart
  namespace: demo
spec:
  type: Restart
  databaseRef:
    name: mssql-standalone
  timeout: 3m
  apply: IfReady