apiVersion: ops.kubedb.com/v1alpha1
kind: MSSQLServerOpsRequest
metadata:
  name: msops-update-ag
  namespace: demo
spec:
  type: UpdateVersion
  databaseRef:
    name: mssql-ag
  updateVersion:
    targetVersion: 2022-cu16
  timeout: 5m
  apply: IfReady