apiVersion: ops.kubedb.com/v1alpha1
kind: MSSQLServerOpsRequest
metadata:
  name: vertical-ag2
  namespace: demo
spec:
  type: VerticalScaling
  databaseRef:
    name: mssqlserver-ag
  verticalScaling:
    mssqlserver:
      resources:
        requests:
          memory: "3Gi"
          cpu: "1000m"
        limits:
          memory: "3Gi"
          cpu: "1000m"