apiVersion: ops.kubedb.com/v1alpha1
kind: MSSQLServerOpsRequest
metadata:
  name: mops-vscale-ag-cluster
  namespace: demo
spec:
  type: VerticalScaling
  databaseRef:
    name: mssql-ag
  verticalScaling:
    mssqlserver:
      resources:
        requests:
          memory: "2Gi"
          cpu: "1m"
        limits:
          cpu: 2
          memory: "4Gi"