apiVersion: ops.kubedb.com/v1alpha1
kind: MSSQLServerOpsRequest
metadata:
  name: ms-online-volume-expansion
  namespace: demo
spec:
  type: VolumeExpansion  
  databaseRef:
    name: mssql-standalone
  volumeExpansion:   
    mode: "Online"
    mssqlserver: 2Gi
