apiVersion: ops.kubedb.com/v1alpha1
kind: MSSQLServerOpsRequest
metadata:
  name: ms-offline-ag
  namespace: demo
spec:
  type: VolumeExpansion  
  databaseRef:
    name: mssqlserver-ag
  volumeExpansion:   
    mode: "Offline" #"Offline"
    mssqlserver: 11Gi
