apiVersion: ops.kubedb.com/v1alpha1
kind: RedisOpsRequest
metadata:
  name: rd-online-volume-expansion4
  namespace: demo
spec:
  type: VolumeExpansion
  databaseRef:
    name: redis-standalone
  volumeExpansion:
    mode: "Online"
    redis: 3Gi
