apiVersion: kubedb.com/v1alpha2
kind: MSSQL
metadata:
  name: ag
  namespace: demo
spec:
  version: "2022-cu12"
  replicas: 2
  authSecret:
    name: mssql-custom-auth
    externallyManaged: true
  internalAuth:
    endpointCert:
      issuerRef:
        apiGroup: cert-manager.io
        name: mssql-ca-issuer
        kind: Issuer
  topology:
    mode: AvailabilityGroup
    availabilityGroup:
      databases:
        - AgDB1
        - AgDB2
  # leaderElection:
  #   period: 100ms
  #   electionTick: 10
  #   heartbeatTick: 1
  #   transferLeadershipInterval: 1s
  #   transferLeadershipTimeout: 60s
  storageType: Durable
  storage:
    storageClassName: "standard"
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
  terminationPolicy: Delete # Halt
