apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubedb-provisioner-caproviderclasses-binding
subjects:
- kind: ServiceAccount
  name: kubedb-provisioner
  namespace: kubedb
roleRef:
  kind: ClusterRole
  name: caproviderclasses-viewer
  apiGroup: rbac.authorization.k8s.io
