apiVersion: kubedb.com/v1alpha2
kind: MSSQLServer
metadata:
  name: ms-stand-monitor
  namespace: demo
spec:
  version: "2022-cu12"
  replicas: 1
  authSecret:
    name: mssql-auth
    externallyManaged: true
  monitor:
    agent: prometheus.io/operator
    prometheus:
      serviceMonitor:
        labels:
          release: prometheus
      exporter:
        # args:
        # - --redis.password=$(REDIS_PASSWORD)
        # env:
        # - name: REDIS_PASSWORD
        #   valueFrom:
        #     secretKeyRef:
        #       name: _name_of_secret_with_redis_password
        #       key: password # key with the password
        resources:
          requests:
            memory: 512Mi
            cpu: 200m
          limits:
            memory: 512Mi
            cpu: 250m
        # securityContext:
        #   runAsUser: 2000
        #   allowPrivilegeEscalation: false
  storageType: Durable
  storage:
    storageClassName: "standard"
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
  terminationPolicy: WipeOut
