apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubedb-provisioner-binding
subjects:
- kind: ServiceAccount
  name: kubedb-provisioner
  namespace: kubedb
roleRef:
  kind: ClusterRole
  name: kubedb-provisioner-new-cluster-role
  apiGroup: rbac.authorization.k8s.io
