apiVersion: kubedb.com/v1alpha2
kind: MSSQLServer
metadata:
  name: mssql-standalone
  namespace: demo
spec:
  version: "2022-cu12"
  # configSecret:
  #   name: ms-config
  replicas: 1
  storageType: Durable
  tls:
    issuerRef:
      name: mssqlserver-ca-issuer
      kind: Issuer
      apiGroup: "cert-manager.io"
    # certificates:
    # - alias: client
      # ipAddresses:
      # - 127.0.0.1
      # - 192.168.0.252
      # secretName: mssqlserver-ag-cluster-client-cert
      # subject:
      #   organizationalUnits:
      #   - client
      #   organizations:
      #   - kubedb
    clientTLS: false
  podTemplate:
    spec:
      terminationGracePeriodSeconds: 300  # Increase this value as needed
      containers:
      - name: mssql
        env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: MSSQL_PID
          value: Evaluation
        resources:
          requests:
            cpu: "500m"
            memory: "1.5Gi"
          limits:
            memory: "2Gi"
  # monitor:
  #   agent: prometheus.io/operator
  #   prometheus:
  #     exporter:
  #       port: 9399
  #     serviceMonitor:
  #       labels:
  #         release: prometheus
  #       interval: 10s
  storage:
    storageClassName: "longhorn"
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
  deletionPolicy: WipeOut



        # env:
        # - name: MSSQL_SA_PASSWORD
        #   value: Pa55w0rd!!
        # resources:
        #   requests:
        #     cpu: "2"
        #     memory: "4Gi"
        #  limits:
        #     cpu: "2"
        #     memory: "6Gi"  # Adjust this value based on the actual needs and node capacity