apiVersion: kubedb.com/v1alpha2
kind: MSSQLServer
metadata:
  name: mssql-standalone5
  namespace: demo
spec:
  version: "2022-cu16"
  storageType: Durable
  tls:
    issuerRef:
      name: mssqlserver-ca-issuer
      kind: Issuer
      apiGroup: "cert-manager.io"
    clientTLS: false
  podTemplate:
    spec:
      containers:
      - name: mssql
        env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: MSSQL_PID
          value: Evaluation
  # monitor:
  #   agent: prometheus.io/operator
  #   prometheus:
  #     exporter:
  #       port: 9399
  #     serviceMonitor:
  #       labels:
  #         release: prometheus
  #       interval: 10s
  storage:
    # storageClassName: "longhorn"
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
  deletionPolicy: WipeOut