apiVersion: kubedb.com/v1alpha2
kind: MSSQLServer
metadata:
  name: ag-passive
  namespace: demo
spec:
  version: "2022-cu16"
  replicas: 3
  # authSecret:
  #   name: mssql-auth
  #   externallyManaged: true
  # configSecret:
  #   name: ms-custom-config
  topology:
    mode: AvailabilityGroup
    availabilityGroup: 
      databases:
        - agdb1
        - agdb2
      secondaryAccess: "NO"
  tls:
    issuerRef:
      name: mssqlserver-ca-issuer
      kind: Issuer
      apiGroup: "cert-manager.io"
    clientTLS: false
  # monitor:
  #   agent: prometheus.io/operator
  #   prometheus:
  #     exporter:
  #       port: 9399
  #     serviceMonitor:
  #       labels:
  #         release: prometheus
  #       interval: 10s
  podTemplate:
    spec:
      containers:
      - name: mssql
        env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: MSSQL_PID
          value: Evaluation
        # resources:
        #   requests:
        #     cpu: "500m"
        #     memory: "1.5Gi"
        #   limits:
        #     memory: "2Gi"
      # - name: mssql-coordinator
      #   env:
      #   - name: GODEBUG
      #     value: "x509negativeserial=1"
  # serviceTemplates:
  # - alias: primary
  #   spec:
  #     type: ClusterIP
  #     ports:
  #       - name: endpoint
  #         port: 5022
  storageType: Durable
  storage:
    # storageClassName: "longhorn"
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
  deletionPolicy: WipeOut
