apiVersion: kubedb.com/v1alpha2
kind: MSSQLServer
metadata:
  name: mssql-ag
  namespace: demo
spec:
  version: "2022-cu12"
  replicas: 3
  # authSecret:
  #   name: mssql-auth
  #   externallyManaged: true
  # configSecret:
  #   name: ms-custom-config
  topology:
    mode: AvailabilityGroup
    availabilityGroup:
      databases:
        - agdb1
        - agdb2
  internalAuth:
    endpointCert:
      issuerRef:
        apiGroup: cert-manager.io
        name: mssqlserver-ca-issuer
        kind: Issuer
  tls:
    issuerRef:
      name: mssqlserver-ca-issuer
      kind: Issuer
      apiGroup: "cert-manager.io"
    clientTLS: false
  # monitor:
  #   agent: prometheus.io/operator
  #   prometheus:
  #     exporter:
  #       port: 9399
  #     serviceMonitor:
  #       labels:
  #         release: prometheus
  #       interval: 10s
  # podTemplate:
  #   spec:
  #     containers:
  #     - name: mssql
  #       resources:
  #         requests:
  #           cpu: "500m"
  #           memory: "1.5Gi"
          # limits:
          #   cpu: "600m"
          #   memory: "1.6Gi"
  storageType: Durable
  storage:
    # storageClassName: "standard"
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
  deletionPolicy: WipeOut
