apiVersion: kubedb.com/v1alpha2
kind: MSSQLServer
metadata:
  name: gg
  namespace: demo
spec:
  deletionPolicy: WipeOut
  healthChecker:
    failureThreshold: 1
    periodSeconds: 10
    timeoutSeconds: 10
  monitor:
    agent: prometheus.io/operator
    prometheus:
      exporter:
        port: 56790
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          runAsGroup: 10001
          runAsNonRoot: true
          runAsUser: 10001
          seccompProfile:
            type: RuntimeDefault
      serviceMonitor:
        interval: 30s
        labels:
          release: kube-prometheus-stack
  podTemplate:
    controller: {}
    metadata: {}
    spec:
      containers:
      - env:
        - name: ACCEPT_EULA
          value: "true"
        - name: MSSQL_PID
          value: Developer
        name: mssql
        # resources:
        #   limits:
        #     cpu: "1"
        #     memory: 1Gi
        #   requests:
        #     cpu: "1"
        #     memory: 1Gi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            add:
            - NET_BIND_SERVICE
            drop:
            - ALL
          runAsGroup: 10001
          runAsNonRoot: true
          runAsUser: 10001
          seccompProfile:
            type: RuntimeDefault
      - name: mssql-coordinator
        resources:
          limits:
            memory: 256Mi
          requests:
            cpu: 200m
            memory: 256Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          runAsGroup: 10001
          runAsNonRoot: true
          runAsUser: 10001
          seccompProfile:
            type: RuntimeDefault
      initContainers:
      - name: mssql-init
        resources:
          limits:
            memory: 512Mi
          requests:
            cpu: 200m
            memory: 256Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          runAsGroup: 10001
          runAsNonRoot: true
          runAsUser: 10001
          seccompProfile:
            type: RuntimeDefault
      nodeSelector:
        kubernetes.io/os: linux
      podPlacementPolicy:
        name: default
      securityContext:
        fsGroup: 10001
      serviceAccountName: gg
  replicas: 3
  storage:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 2Gi
    storageClassName: standard
  storageType: Durable
  tls:
    certificates:
    - alias: server
      secretName: gg-server-cert
      subject:
        organizationalUnits:
        - server
        organizations:
        - kubedb
    - alias: client
      secretName: gg-client-cert
      subject:
        organizationalUnits:
        - client
        organizations:
        - kubedb
    - alias: endpoint
      secretName: gg-endpoint-cert
      subject:
        organizationalUnits:
        - endpoint
        organizations:
        - kubedb
    clientTLS: false
    issuerRef:
      apiGroup: cert-manager.io
      kind: ClusterIssuer
      name: cluster-issuer
  topology:
    availabilityGroup:
      databases: 
        - agdb1
      leaderElection:
        electionTick: 10
        heartbeatTick: 1
        period: 300ms
        transferLeadershipInterval: 1s
        transferLeadershipTimeout: 1m0s
    mode: AvailabilityGroup
  version: 2022-cu12