apiVersion: v1
kind: Service
metadata:
  name: ag2
  namespace: demo
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: primary
    port: 1433
    protocol: TCP
    targetPort: db
  - name: mirroring-endpoint
    port: 5022
    targetPort: 5022
    protocol: TCP
  publishNotReadyAddresses: true
  selector:
    app.kubernetes.io/instance: ag2
    app.kubernetes.io/managed-by: kubedb.com
    app.kubernetes.io/name: mssqlservers.kubedb.com
    kubedb.com/role: primary
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}

---
apiVersion: v1
kind: Service
metadata:
  name: ag1
  namespace: demo
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: primary
    port: 1433
    protocol: TCP
    targetPort: db
  - name: mirroring-endpoint
    port: 5022
    targetPort: 5022
    protocol: TCP
  publishNotReadyAddresses: true
  selector:
    app.kubernetes.io/instance: ag1
    app.kubernetes.io/managed-by: kubedb.com
    app.kubernetes.io/name: mssqlservers.kubedb.com
    kubedb.com/role: primary
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
