apiVersion: catalog.kubedb.com/v1alpha1
kind: MSSQLServerVersion
metadata:
  name: 2022-cu16
spec:
  archiver:
    addon:
      name: mssqlserver-addon
      tasks:
        fullBackup:
          name: logical-backup
        fullBackupRestore:
          name: logical-backup-restore
        manifestBackup:
          name: manifest-backup
        manifestRestore:
          name: manifest-restore
    walg:
      image: ghcr.io/kubedb/mssqlserver-archiver:v0.7.0
  coordinator:
    image: neajmorshad/mssql-coordinator:passive-replica_linux_amd64
  db:
    image: mcr.microsoft.com/mssql/server:2022-CU16-ubuntu-22.04
  exporter:
    image: ghcr.io/kubedb/mssql-exporter:1.1.0
  initContainer:
    image: ghcr.io/kubedb/mssql-init:2022-ubuntu-22-v3
  securityContext:
    runAsUser: 10001
  version: "2022"
