apiVersion: kubedb.com/v1
kind: ProxySQL
metadata:
  name: mariadb-proxy
  namespace: demo
spec:
  version: "2.7.3-debian"
  replicas: 1
  syncUsers: true
  backend:
    name: mariadb-galera
  deletionPolicy: WipeOut


---

apiVersion: kubedb.com/v1
kind: ProxySQL
metadata:
  name: mariadb-proxy11
  namespace: demo
spec:
  version: "2.7.3-debian"
  replicas: 1
  syncUsers: true
  backend:
    name: mariadb11
  deletionPolicy: WipeOut