apiVersion: kubedb.com/v1
kind: ProxySQL
metadata:
  name: mysql-proxy2
  namespace: demo
spec:
  version: 2.6.3-debian # 2.3.2-debian # "2.6.3-debian"
  replicas: 3
  syncUsers: true
  backend:
    name: mysql-server
  deletionPolicy: WipeOut