apiVersion: kubedb.com/v1alpha2
kind: MsSQL
metadata:
  name: mssql-std
  namespace: demo
spec:
  version: "2022-CU11-ubuntu-22.04"  # Specify the desired version, e.g., "2019-CU12-GDR" or "2017-CU24-GDR"
  replicas: 1        # Number of instances to deploy
  storageType: Durable
  storage:
    storageClassName: "standard"
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
  terminationPolicy: Halt
