apiVersion: core.kubestash.com/v1alpha1
kind: BackupConfiguration
metadata:
  name: redis-bc-cluster
  namespace: demo
spec:
  paused: true
  target:
    apiGroup: kubedb.com
    kind: Redis
    namespace: demo
    name: redis-cluster-v1 # redis-cluster-v1 # rd-stand-v1
  backends:
    - name: s3-backend
      storageRef:
        namespace: demo
        name: s3-storage
      retentionPolicy:
        name: demo-retention-policy
        namespace: demo
  sessions:
    - name: frequent-backup
      sessionHistoryLimit: 3
      scheduler:
        schedule: "*/1 * * * *"
        successfulJobsHistoryLimit: 1
        failedJobsHistoryLimit: 1
        jobTemplate:
          backoffLimit: 1
      repositories:
        - name: s3-repo-cluster2 # s3-repo-stand # s3-repo-cluster
          backend: s3-backend
          directory: /redis-dir-cluster2 # /redis-dir-stand # /redis-dir-cluster
          encryptionSecret:
           name: encry-secret # some addon may not support encryption
           namespace: demo
      addon:
        name: redis-addon
        tasks:
          - name: logical-backup

