apiVersion: core.kubestash.com/v1alpha1
kind: BackupConfiguration
metadata:
  name: rd-backup-config
  namespace: demo
spec:
  paused: true
  target:
    apiGroup: kubedb.com
    kind: Redis
    namespace: demo
    name: rd-sentinel-v1 # rd-stand-v1 # rd-cluster-v1 # rd-stand-v1
  backends:
    - name: s3-backend
      storageRef:
        namespace: demo
        name: s3-storage
      retentionPolicy:
        name: demo-retention-policy
        namespace: demo
  sessions:
    - name: frequent-backup
      sessionHistoryLimit: 3
      scheduler:
        schedule: "*/1 * * * *"
        successfulJobsHistoryLimit: 1
        failedJobsHistoryLimit: 1
        jobTemplate:
          backoffLimit: 1
          template:
            spec:
              securityContext:
                runAsUser: 65535
                runAsNonRoot: true
                seccompProfile:
                  type: RuntimeDefault
              containerSecurityContext:
                allowPrivilegeEscalation: false
                capabilities:
                  drop:
                    - ALL
      repositories:
        - name: s3-repo-sen-new # s3-repo-stad
          backend: s3-backend
          directory: /redis-dir-sen-new # /redis-dir-stad
          encryptionSecret:
           name: encry-secret # some addon may not support encryption
           namespace: demo
      addon:
        name: redis-addon
        tasks:
          - name: logical-backup
        jobTemplate:
          spec: 
            securityContext: 
              runAsUser: 65535
              runAsNonRoot: true
              seccompProfile:
                type: RuntimeDefault
            containerSecurityContext:
                allowPrivilegeEscalation: false
                capabilities:
                  drop:
                    - ALL