apiVersion: core.kubestash.com/v1alpha1
kind: RestoreSession
metadata:
  name: redis-restore
  namespace: demo
spec:
  target:
    name: redis-cluster-v1-res
    namespace: demo
    apiGroup: kubedb.com
    kind: Redis
  dataSource:
    snapshot: latest
    repository: s3-repo-cluster
    encryptionSecret:
      name: encry-secret 
      namespace: demo
  addon:
    name: redis-addon
    tasks:
      - name: logical-backup-restore
