apiVersion: core.kubestash.com/v1alpha1
kind: RestoreSession
metadata:
  name: rd-stand-res
  namespace: demo
spec:
  target:
    name: rd-sentinel-v1-res # rd-stand-v1-res # redis-cluster-v1-res
    namespace: demo
    apiGroup: kubedb.com
    kind: Redis
  dataSource:
    snapshot: latest
    repository: s3-repo-sen-new # s3-repo-stand # s3-repo-cluster
    encryptionSecret:
      name: encry-secret 
      namespace: demo
  addon:
    name: redis-addon
    tasks:
      - name: logical-backup-restore
    jobTemplate:
      spec: 
        securityContext: 
          runAsUser: 65535
          runAsNonRoot: true
          seccompProfile:
            type: RuntimeDefault
        containerSecurityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL