apiVersion: ops.kubedb.com/v1alpha1
kind: RedisOpsRequest
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"ops.kubedb.com/v1alpha1","kind":"RedisOpsRequest","metadata":{"annotations":{},"name":"rd-sentinel-add-tls","namespace":"demo"},"spec":{"databaseRef":{"name":"rd-sentinel"},"tls":{"certificates":[{"alias":"client","subject":{"organizationalUnits":["client"],"organizations":["redis"]}}],"issuerRef":{"apiGroup":"cert-manager.io","kind":"ClusterIssuer","name":"redis-ca-issuer"},"sentinel":{"ref":{"name":"sen-demo-tls","namespace":"demo"},"removeUnusedSentinel":true}},"type":"ReconfigureTLS"}}
  creationTimestamp: "2023-08-04T13:14:14Z"
  generation: 1
  name: rd-sentinel-add-tls
  namespace: demo
  resourceVersion: "497919"
  uid: c6b4042f-cf8f-4bda-9e84-6bb4a6ee67c5
spec:
  apply: IfReady
  databaseRef:
    name: rd-sentinel
  tls:
    certificates:
    - alias: client
      subject:
        organizationalUnits:
        - client
        organizations:
        - redis
    issuerRef:
      apiGroup: cert-manager.io
      kind: ClusterIssuer
      name: redis-ca-issuer
    sentinel:
      ref:
        name: sen-demo-tls
        namespace: demo
      removeUnusedSentinel: true
  type: ReconfigureTLS
status:
  conditions:
  - lastTransitionTime: "2023-08-04T13:14:14Z"
    message: Redis ops request is reconfiguring TLS
    observedGeneration: 1
    reason: ReconfigureTLS
    status: "True"
    type: ReconfigureTLS
  - lastTransitionTime: "2023-08-04T13:16:24Z"
    message: Successfully Replaced Sentinel
    observedGeneration: 1
    reason: ReplaceSentinel
    status: "True"
    type: ReplaceSentinel
  - lastTransitionTime: "2023-08-04T13:16:29Z"
    message: Successfully synced all certificates
    observedGeneration: 1
    reason: CertificateSynced
    status: "True"
    type: CertificateSynced
  - lastTransitionTime: "2023-08-04T13:18:19Z"
    message: Successfully restarted pods
    observedGeneration: 1
    reason: RestartPods
    status: "True"
    type: RestartPods
  - lastTransitionTime: "2023-08-04T13:18:19Z"
    message: Successfully reconfigured TLS
    observedGeneration: 1
    reason: Successful
    status: "True"
    type: Successful
  observedGeneration: 1
  phase: Successful
