apiVersion: v1
kind: Service
metadata:
  name: milvus-etcd-headless # This name MUST match the serviceName in the StatefulSet
  namespace: milvus-standalone
spec:
  clusterIP: None # This line is what makes the service "headless"
  selector:
    app: milvus
    component: etcd
  ports:
  - port: 2379
    targetPort: 2379
---
# Service to give etcd a stable network address.
apiVersion: v1
kind: Service
metadata:
  name: milvus-etcd
  namespace: milvus-standalone
spec:
  selector:
    app: milvus
    component: etcd
  ports:
  - port: 2379
    targetPort: 2379
---
# 2. DEPENDENCY: ETCD (METADATA STORAGE)
# We use a StatefulSet because etcd needs stable network identity and storage.
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: milvus-etcd
  namespace: milvus-standalone
spec:
  serviceName: milvus-etcd-headless
  replicas: 1
  selector:
    matchLabels:
      app: milvus
      component: etcd
  template:
    metadata:
      labels:
        app: milvus
        component: etcd
    spec:
      containers:
      - name: etcd
        image: quay.io/coreos/etcd:v3.5.5    #  helm chart image: docker.io/milvusdb/etcd:3.5.5-r2
        command:
        - /usr/local/bin/etcd
        - --name=etcd-0
        - --listen-client-urls=http://0.0.0.0:2379
        - --advertise-client-urls=http://milvus-etcd-0.milvus-etcd-headless:2379
        - --data-dir=/etcd-data
        ports:
        - containerPort: 2379
        volumeMounts:
        - name: etcd-data
          mountPath: /etcd-data
  volumeClaimTemplates:
  - metadata:
      name: etcd-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi
---
# Service to give MinIO a stable network address.
apiVersion: v1
kind: Service
metadata:
  name: milvus-minio
  namespace: milvus-standalone
spec:
  selector:
    app: milvus
    component: minio
  ports:
  - name: api
    port: 9000
    targetPort: 9000
  - name: console
    port: 9001
    targetPort: 9001
---
# Request storage (a PVC) for MinIO's data.
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-pvc
  namespace: milvus-standalone
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
---
# 3. DEPENDENCY: MINIO (OBJECT STORAGE)
# We use a Deployment as we only need one simple instance for standalone mode.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: milvus-minio
  namespace: milvus-standalone
spec:
  replicas: 1
  selector:
    matchLabels:
      app: milvus
      component: minio
  template:
    metadata:
      labels:
        app: milvus
        component: minio
    spec:
      containers:
      - name: minio
        image: minio/minio:RELEASE.2023-03-20T20-16-18Z   # helm chart image: minio/minio:RELEASE.2023-03-20T20-16-18Z   https://hub.docker.com/r/minio/minio
        command:
        - /bin/bash
        - -c
        - minio server /data --console-address :9001
        env:
        - name: MINIO_ROOT_USER
          value: "minioadmin"
        - name: MINIO_ROOT_PASSWORD
          value: "minioadmin"
        ports:
        - containerPort: 9000 # API port
        - containerPort: 9001 # Console port
        volumeMounts:
        - name: minio-data
          mountPath: /data
      volumes:
      - name: minio-data
        persistentVolumeClaim:
          claimName: minio-pvc