apiVersion: kubedb.com/v1
kind: MariaDB
metadata:
  name: mariadb-server
  namespace: demo
spec:
  version: "10.6.16"
  replicas: 3
  storageType: Durable
  storage:
    storageClassName: "standard"
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
  deletionPolicy: WipeOut