# milvus-standalone.yaml
# 5. THE MILVUS SERVICE
# This exposes the Milvus gRPC port so we can connect to it.
apiVersion: v1
kind: Service
metadata:
  name: milvus-standalone
  namespace: milvus-standalone
spec:
  selector:
    app: milvus
    component: standalone
  ports:
  - name: grpc
    port: 19530
    targetPort: 19530
---
# 4. THE MILVUS STANDALONE DEPLOYMENT
# This is the main application. It's stateless because its state is in etcd and minio.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: milvus-standalone
  namespace: milvus-standalone
spec:
  replicas: 1
  selector:
    matchLabels:
      app: milvus
      component: standalone
  template:
    metadata:
      labels:
        app: milvus
        component: standalone
    spec:
      containers:
      - name: milvus
        image: milvusdb/milvus:v2.6.1
        command: ["/tini", "--", "/milvus/bin/milvus", "run", "standalone"]
        env:
        - name: ETCD_ENDPOINTS
          value: milvus-etcd:2379
        - name: MINIO_ADDRESS
          value: milvus-minio:9000
        - name: COMMON_STORAGETYPE
          value: "local"
        ports:
        - containerPort: 19530 # gRPC port
        - containerPort: 9091  # Metrics port
        volumeMounts:
        - name: milvus-config-volume
          mountPath: /milvus/configs/milvus.yaml
          subPath: milvus.yaml
      volumes:
      - name: milvus-config-volume
        configMap:
          name: milvus-config