apiVersion: kubedb.com/v1
kind: MySQL
metadata:
  name: mysql843
  namespace: demo
spec:
  version: 8.4.3
  replicas: 3
  topology:
    mode: GroupReplication
  storageType: Durable
  storage:
    storageClassName: "standard"
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
  deletionPolicy: WipeOut