apiVersion: kubedb.com/v1
kind: MySQL
metadata:
  name: mysql-server2
  namespace: demo
spec:
  version: 8.0.36 # "9.1.0"
  replicas: 3
  topology:
    mode: GroupReplication
  storageType: Durable
  storage:
    storageClassName: "standard"
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
  deletionPolicy: WipeOut