apiVersion: kubedb.com/v1
kind: MariaDB
metadata:
  name: mariadb-galera
  namespace: demo
spec:
  version: "10.6.16" # 11.6.2
  replicas: 3
  storageType: Durable
  storage:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
  deletionPolicy: WipeOut