apiVersion: kubedb.com/v1alpha2
kind: RedisSentinel
metadata:
  name: johntest-redis
  namespace: john
spec:
  version: 6.2.8
  replicas: 3
  storageType: Durable
  storage:
    resources:
      requests:
        storage: 1Gi
    storageClassName: "standard"
    accessModes:
    - ReadWriteOnce
  terminationPolicy: WipeOut
