apiVersion: ops.kubedb.com/v1alpha1
kind: RedisOpsRequest
metadata:
  name: rdops-apply-reconfig
  namespace: demo
spec:
  type: Reconfigure
  databaseRef:
    name: rd-std
  configuration:
    applyConfig:
      redis.conf: |-
        maxclients 3000    