apiVersion: ops.kubedb.com/v1alpha1
kind: RedisOpsRequest
metadata:
  name: horizontal-down
  namespace: demo
spec:
  type: HorizontalScaling
  databaseRef:
    name: rd-cluster-v1
  horizontalScaling:
    replicas: 2
