apiVersion: ops.kubedb.com/v1alpha1
kind: RedisOpsRequest
metadata:
  name: horizontal-up
  namespace: demo
spec:
  type: HorizontalScaling
  databaseRef:
    name: redis-cluster-v1
  horizontalScaling:
    shards: 3
