apiVersion: ops.kubedb.com/v1alpha1
kind: RedisOpsRequest
metadata:
  name: rd-std-reconfigure
  namespace: demo
spec:
  type: Reconfigure
  databaseRef:
    name: rd-std
  configuration:
      configSecret:
        name: new-custom-config
