apiVersion: ops.kubedb.com/v1alpha1
kind: RedisOpsRequest
metadata:
  name: rdops-reconfig-apply-config
  namespace: demo
spec:
  type: Reconfigure
  databaseRef:
    name: sample-redis
  configuration:
    applyConfig:
      redis.conf: |-
        maxclients 3000
  timeout: 5m
  apply: IfReady
