apiVersion: ops.kubedb.com/v1alpha1
kind: RedisOpsRequest
metadata:
  name: rd-online
  namespace: demo
spec:
  type: VolumeExpansion  
  databaseRef:
    name: rd-stand-v1
  volumeExpansion:   
    mode: "Online"
    redis: 11Gi