apiVersion: ops.kubedb.com/v1alpha1
kind: RedisSentinelOpsRequest
metadata:
  name: redissentinel-vertical
  namespace: demo
spec:
  type: VerticalScaling
  databaseRef:
    name: sen-demo
  verticalScaling:
    redissentinel:
      requests:
        memory: "300Mi"
        cpu: "200m"
      limits:
        memory: "300Mi"
        cpu: "200m"
