apiVersion: stash.appscode.com/v1beta1
kind: BackupBlueprint
metadata:
  name: redis-backup-template
spec:
  # ============== Blueprint for Repository ==========================
  backend:
    s3:
      endpoint: 'https://minio-service.demo.svc' # Use your own Minio server address.
      bucket: minio-bucket  # Give a name of the bucket where you want to backup.
      prefix: redis-backup/${TARGET_NAMESPACE}/${TARGET_APP_RESOURCE}/${TARGET_NAME} # Path prefix into bucket where repository will be created.(optional).
    storageSecretName: minio-restic-secret
  # ============== Blueprint for BackupConfiguration =================
  schedule: "*/5 * * * *"
  retentionPolicy:
    name: 'keep-last-5'
    keepLast: 5
    prune: true