apiVersion: stash.appscode.com/v1alpha1
kind: Repository
metadata:
  name: minio-repo
  namespace: demo
spec:
  backend:
    s3:
      endpoint: 'https://minio-service.demo.svc' # Use your own Minio server address.
      bucket: minio-bucket  # Give a name of the bucket where you want to backup.
      prefix: path-prefix-stash # Path prefix into bucket where repository will be created.(optional).
    storageSecretName: minio-restic-secret
